// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-leads.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-leads.ts
var LEAD_FIELDS = "id, business_name, contact_name, email, phone, website, linkedin_url, industry, city, state, zip_code, company_size, estimated_revenue, lead_score, status, source_url, notes, created_at, updated_at";
var search_leads_default = defineTool({
  name: "search_leads",
  title: "Search leads",
  description: "Search the signed-in user's Brivano leads by free text, status, industry, city or state. Returns contact details, company, score and status.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free text matched against company name, contact name and email."),
    status: z.string().trim().optional().describe("Lead status filter, e.g. new, contacted, qualified, converted."),
    industry: z.string().trim().optional().describe("Industry filter (partial match)."),
    city: z.string().trim().optional().describe("City filter (partial match)."),
    state: z.string().trim().optional().describe("State filter (partial match)."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, industry, city, state, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let request = supabase.from("leads").select(LEAD_FIELDS).order("created_at", { ascending: false }).limit(take);
    if (query) {
      const escaped = query.replace(/[%,()]/g, " ").trim();
      if (escaped) {
        request = request.or(
          `business_name.ilike.%${escaped}%,contact_name.ilike.%${escaped}%,email.ilike.%${escaped}%`
        );
      }
    }
    if (status) request = request.eq("status", status);
    if (industry) request = request.ilike("industry", `%${industry}%`);
    if (city) request = request.ilike("city", `%${city}%`);
    if (state) request = request.ilike("state", `%${state}%`);
    const { data, error } = await request;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead",
  description: "Fetch one Brivano lead by id, including its full contact details, score, status and notes.",
  inputSchema: {
    lead_id: z2.string().trim().min(1).describe("The lead's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").select(LEAD_FIELDS).eq("id", lead_id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No lead found with id ${lead_id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool3({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in Brivano for the signed-in user. Company (business) name is required; every other field is optional.",
  inputSchema: {
    business_name: z3.string().trim().min(1).describe("Company / account name."),
    contact_name: z3.string().trim().optional().describe("Full name of the person."),
    email: z3.string().trim().optional().describe("Contact email address."),
    phone: z3.string().trim().optional().describe("Contact phone number."),
    website: z3.string().trim().optional().describe("Company website URL."),
    linkedin_url: z3.string().trim().optional().describe("LinkedIn profile URL."),
    industry: z3.string().trim().optional().describe("Industry of the company."),
    city: z3.string().trim().optional(),
    state: z3.string().trim().optional(),
    notes: z3.string().trim().optional().describe("Free-form notes about the lead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError3("Could not resolve the signed-in user");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").insert({ ...input, client_id: userId }).select(LEAD_FIELDS).single();
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/update-lead.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var update_lead_default = defineTool4({
  name: "update_lead",
  title: "Update lead",
  description: "Update an existing Brivano lead: change its status, score, notes or contact details. Only the provided fields are changed.",
  inputSchema: {
    lead_id: z4.string().trim().min(1).describe("The lead's UUID."),
    status: z4.string().trim().optional().describe("New status, e.g. new, contacted, qualified, converted, rejected."),
    contact_name: z4.string().trim().optional(),
    email: z4.string().trim().optional(),
    phone: z4.string().trim().optional(),
    website: z4.string().trim().optional(),
    linkedin_url: z4.string().trim().optional(),
    industry: z4.string().trim().optional(),
    city: z4.string().trim().optional(),
    state: z4.string().trim().optional(),
    lead_score: z4.number().optional().describe("Lead score between 0 and 100."),
    notes: z4.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, ...updates }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const payload = Object.fromEntries(
      Object.entries(updates).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(payload).length === 0) {
      throw new ToolError4("Provide at least one field to update");
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").update(payload).eq("id", lead_id).select(LEAD_FIELDS).maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4(`No lead found with id ${lead_id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-campaigns.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_campaigns_default = defineTool5({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List the signed-in user's Brivano email campaigns with their id, name, description and active state.",
  inputSchema: {
    active_only: z5.boolean().optional().describe("When true, return only campaigns that are currently active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("email_campaigns").select("id, name, description, is_active, created_at").order("created_at", { ascending: false });
    if (active_only) request = request.eq("is_active", true);
    const { data, error } = await request;
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/enroll-lead-in-campaign.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var enroll_lead_in_campaign_default = defineTool6({
  name: "enroll_lead_in_campaign",
  title: "Enroll lead in campaign",
  description: "Enroll one of the signed-in user's Brivano leads into an email campaign so it starts receiving the sequence.",
  inputSchema: {
    lead_id: z6.string().trim().min(1).describe("The lead's UUID."),
    campaign_id: z6.string().trim().min(1).describe("The campaign's UUID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, campaign_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: existing, error: existingError } = await supabase.from("lead_campaign_enrollments").select("id, status").eq("lead_id", lead_id).eq("campaign_id", campaign_id).maybeSingle();
    if (existingError) throw new ToolError6(existingError.message);
    if (existing) {
      return {
        content: [
          { type: "text", text: `Lead is already enrolled (status: ${existing.status}).` }
        ],
        structuredContent: { enrollment: existing, already_enrolled: true }
      };
    }
    const { data, error } = await supabase.from("lead_campaign_enrollments").insert({ lead_id, campaign_id, status: "active", current_step: 0 }).select("id, lead_id, campaign_id, status, current_step, enrolled_at").single();
    if (error) throw new ToolError6(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { enrollment: data, already_enrolled: false }
    };
  }
});

// src/lib/mcp/tools/get-account-leads.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var get_account_leads_default = defineTool7({
  name: "get_account_leads",
  title: "Get account leads",
  description: "List every Brivano lead associated with a company / account name, so you can see all contacts at that company.",
  inputSchema: {
    company_name: z7.string().trim().min(1).describe("Company / account name (partial match is allowed)."),
    limit: z7.number().int().optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 50, 1), 200);
    const escaped = company_name.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("leads").select(LEAD_FIELDS).ilike("business_name", `%${escaped}%`).order("lead_score", { ascending: false, nullsFirst: false }).limit(take);
    if (error) throw new ToolError7(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { company_name, count: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eotfijnsfwroukhjwsbe";
var mcp_default = defineMcp({
  name: "brivano-leads",
  title: "Brivano Leads",
  version: "0.1.0",
  instructions: "Tools for Brivano, a B2B lead generation and CRM workspace. Use `search_leads` and `get_account_leads` to find leads, `get_lead` for full detail, `create_lead` and `update_lead` to manage records, and `list_campaigns` + `enroll_lead_in_campaign` to run outreach. All tools act as the signed-in Brivano user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_leads_default,
    get_account_leads_default,
    get_lead_default,
    create_lead_default,
    update_lead_default,
    list_campaigns_default,
    enroll_lead_in_campaign_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
